spring:
  rabbitmq:
    host: localhost
    port: 5672
    listener:
      prefetch: 0
      acknowledge-mode: auto
    virtual-host: /rabbit-gst
    cache:
      channel:
        size: 30
    dynamic: true
